[build]
  command = "./cloudflare-build.sh"
  publish = "dist"
  node_bundler = "vite"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-package-lock --no-audit --prefer-offline"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
